github_PAT: 5aacbb16b7a6fdd68e4892b88d7647de63f14450
subscription: 3a8cae91-4f30-403a-846d-4746b0a26e5b
resource_group: Demo4ResGrp
resource: Demo4Res

----------ONLY GIVE INPUTS IN THE SPACE PROVIDED TO THE RIGHT SIDE OF EVERY FIELD ABOVE.... DO NOT CHANGE ANYTHING ELSE-------------
Getting Started:
  - Run the following command in your terminal from the repository you want to deploy => node node_modules/@shubham-agarwal-27/hooks-deploy-to-azure
  - Files/Folders created:-
    - A templates folder:- that will be used for getting the workflow file.
    - A workflow_inputs.txt file:- You are required to give the necessary inputs inside this file before starting with deploying your app.
    - A pre-commit hook:- This is present inside the .git/hooks folder (If you had any pre-exisiting hook with the same name, it gets saved as pre-commit.bkp)
    - A pre-push hook:- This is present inside the .git/hooks folder (If you had any pre-exisiting hook with the same name, it gets saved as pre-push.bkp)
    - An open_workflow_run file:- This is a JavaScript file which can be run after you are done with pushing your contents to GitHub. This will take you to the workflow run you triggered on the last push.
    - Apart from the files created, the .gitignore file is appended with the name of the files/folders so that no sensitive information is pushed to your GitHub account.

How to Deploy?:
  - First, you need to give the following MANDATORY inputs in this file in the space provided at the top:

    - GitHub PAT Token:
      - Repo scope needed.
      - Visit (https://github.com/shubham-agarwal-27/hooks-deploy-to-azure/blob/master/README.md#github-pat) to know how to get a GitHub APT Token.
    
    - Azure Tenant ID:
      - Visit (https://github.com/shubham-agarwal-27/hooks-deploy-to-azure/blob/master/README.md#azure-tenant-id) to know how to get your Azure Tenant ID.

    - Subscription ID:
      - Visit (https://github.com/shubham-agarwal-27/hooks-deploy-to-azure/blob/master/README.md#subscription-id) to know how to get a subscription

  - Next, you have two optional fields:

    - Resource Group:
      - Visit (https://github.com/shubham-agarwal-27/hooks-deploy-to-azure/blob/master/README.md#resource-group) to know how to get a resource group name

    - Resource:
      - Visit (https://github.com/shubham-agarwal-27/hooks-deploy-to-azure/blob/master/README.md#resource) to know how to get a resource name

